#
# This is the configuration file.
#
# This file will be used to generate header-files and other configuration files
# for the system during compile time. Therefore, change only values located here
# and not in the config files scattered around in the project or those who were
# created as a product of this file

TEST: 4
# Multiprocess 
N_THREADS: 8
SHM_PATH: "/shared_memory_bf"
MAX_VALUE_FLOAT: "(float)(1 << 23)"

# Physics speficic constants 

PROPAGATION_SPEED: 340.0 # Speed of sound in air


TEST_PLOT: true
CYTHON_ANNOTATE: false # If should annotate code
CYTHON_CACHE: true
CYTHON_BOUNDS_CHECK: false # Check list slicing

  


