#
# This is the configuration file.
#
# This file will be used to generate header-files and other configuration files
# for the system during compile time. Therefore, change only values located here
# and not in the config files scattered around in the project or those who were
# created as a product of this file



# Beamforming 

# Heatmap (MIMO)
USE_MIMO: false
X_RES: 1024
Y_RES: 1024
RESIZE_HEATMAP: false

# Application
APPLICATION_NAME: "Beamforming"
APPLICATION_WIDTH: 1024
APPLICATION_HEIGHT: 1024

RESOLUTION_MULTIPLIER: 16 # times the initial resolution

BLUR_KERNEL_SIZE: 5 # Kernel size of blur on heatmap

# Waraps client
USE_WARAPS: true
WARAPS_NAME: "test"
WARAPS_ADDRESS: "mqtt://test.mosquitto.org:1883"



# Antenna
COLUMNS: 8
ROWS: 8
ELEMENTS: COLUMNS * ROWS
DISTANCE: 0.02 # Distance between each element to the next


# FPGA 
SAMPLE_RATE: 48828.0 
PROTOCOL_VERSION: 2 # This must match the version located on the FPGA
MAX_N_SENSORS: ROWS * COLUMNS * 4 
N_FPGAS: 1 # How many running FPGAs
IP_ADDRESSES: # Does not need to be edited if N_FPGAS is edited, only if you have different src addresses fo the FPGAS
  - '127.0.0.1'


# Beamforming 
N_FRAMES: 4 # How many "frames" that are stored in the ringbuffer 
N_SAMPLES: 256 #16384 # 512 # Each frame, must be a power of 2 
N_OFFSET: N_SAMPLES / 2
BUFFER_LENGTH: N_FRAMES * N_SAMPLES


# Optimizations
LOCAL_AREA_RATIO: 0.7
GLOBAL_AREA_RATIO: 1.0 - LOCAL_AREA_RATIO

# Camera
FOV: 45.0 # How far we should look to the side
CAMERA: false
CAMERA_PATH: "/dev/video0"

# Heatmaps
IMAGE_CURRENT_WEIGHTED_RATIO: 0.1
IMAGE_PREVIOUS_WEIGHTED_RATIO: 1.0 - IMAGE_CURRENT_WEIGHTED_RATIO


# Beamforming
PI: 3.1415926535897
TWO_PI: 2.0 * PI
ANGLE_LIMIT: FOV * PI / 180.0 #PI / 4.0 * 2.0

USE_KALMAN_FILTER: true

# Audio 
AUDIO: false
USE_AUDIO: AUDIO


# Networking 
#UDP_ADDRESS: "10.0.0.1"
UDP_ADDRESS: "127.0.0.1"
#UDP_PORT: 12345
UDP_PORT: 21844

N_TAPS: 32 # Kernel size

TEST: 4
# Multiprocess 
N_THREADS: 8
SHM_PATH: "/shared_memory_bf"
MAX_VALUE_FLOAT: "(float)(1 << 23)"

# Physics speficic constants 

PROPAGATION_SPEED: 340.0 # Speed of sound in air


TEST_PLOT: true
CYTHON_ANNOTATE: false # If should annotate code
CYTHON_CACHE: true
CYTHON_BOUNDS_CHECK: false # Check list slicing

  


