name: Clang Format and Tidy checks
on:
  push:

jobs:

    clang-tidy:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4

        - name: Install clang-tidy
          run: sudo apt-get install clang-tidy

        - name: Run clang-tidy
          run: clang-tidy --format-style="file" $(find . -name '*.cpp' -or -name '*.h')