name: Docker Image CI and CMake Checks

on:
  pull_request:
    branches: [ "main" ]

jobs:

  build-image:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag beamformer:$(date +%s)
    - name: Run the docker image
      run: docker run -v $(pwd):/usr/src/app -i --network=host -v /tmp/.X11-unix:/tmp/.X11-unix --user=$(id -u $USER) beamformer:$(date +%s) bash
    - name: Build the beamformer using CMake
      run: cmake -S . -B build && cmake --build build
    
