name: Docker Image CI and CMake Checks
on:
  pull_request:
    branches: [ "main" ]

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Pull the Docker image
        run: docker image pull karlkorv/beamformer:latest

      - name: Run cmake in the Docker image
        run: |
          docker run --rm -v ${{ github.workspace }}:/usr/src/app -w /usr/src/app karlkorv/beamformer:latest /bin/bash -c "
            sudo cmake -S . -B /build &&
            sudo cmake --build /build"
