name: Docker Image CI and CMake Checks

on:
  pull_request:
    branches: [ "main" ]

jobs:

  build-image:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag beamformer:$(date +%s)
    - name: Run CMake build in the docker image
      run: docker run --rm beamformer:$(date +%s) /bin/bash -c "mkdir build && cd build && cmake .. && make"
    
